const dotenv   = require('dotenv')
const mongoose = require('mongoose')
const Property = require('./models/Property')

dotenv.config()
mongoose.set('bufferCommands', false)

const cloudinary = 'https://res.cloudinary.com/doqniwpta/image/upload'

const img = {
  apart1:     `${cloudinary}/v1773133314/apart1_eq3asl.jpg`,
  apart2:     `${cloudinary}/v1773133310/apart2_izkytw.jpg`,
  apart3:     `${cloudinary}/v1773133438/apart3_uvs8oq.jpg`,
  architect:  `${cloudinary}/v1773133317/architect_gtmzi6.jpg`,
  commercial: `${cloudinary}/v1773133323/commercial_gecaqi.jpg`,
  duplex:     `${cloudinary}/v1773133323/duplex_nhfity.jpg`,
  duplex3:    `${cloudinary}/v1773133333/duplex3_rybtmy.jpg`,
  im1:        `${cloudinary}/v1773133327/im1_pvk7fl.jpg`,
  im2:        `${cloudinary}/v1773133327/im2_h7wyoo.jpg`,
  im3:        `${cloudinary}/v1773133328/im3_znxsop.webp`,
  int1:       `${cloudinary}/v1773133329/int1_w57mja.jpg`,
  int2:       `${cloudinary}/v1773133336/int2_uzcr1n.jpg`,
  int3:       `${cloudinary}/v1773133331/int3_g22nmz.jpg`,
  int4:       `${cloudinary}/v1773133330/int4_vhgvop.jpg`,
  int5:       `${cloudinary}/v1773133332/int5_zmkhli.webp`,
  kitchen:    `${cloudinary}/v1773133336/kitchen_otuzyb.jpg`,
  livingroom: `${cloudinary}/v1773133311/livingroom_teiy1t.avif`,
  mansion:    `${cloudinary}/v1773133311/mansion_pxhf1f.jpg`,
  myimg1:     `${cloudinary}/v1773133314/myimg1_xhiib4.jpg`,
  penthhouse: `${cloudinary}/v1773133321/penthhouse_rsnytv.png`,
  skyline:    `${cloudinary}/v1773133360/skyline_zykpfk.jpg`,
  studio:     `${cloudinary}/v1773133319/studio_sisth1.jpg`,
  swim:       `${cloudinary}/v1773133321/swim_fia6bk.avif`,
  terra:      `${cloudinary}/v1773133321/terra_wljihp.jpg`,
  villa:      `${cloudinary}/v1773133323/villa_y5pkxn.jpg`,
}

const agent = {
  name:  'Temiloluwa Aderounmu',
  role:  'Senior Property Consultant',
  phone: '09016196558',
  email: 'aderounmutemiloluwa2004@gmail.com',
  image: `${cloudinary}/v1773133314/myimg1_xhiib4.jpg`,
}

const properties = [
  {
    title: 'Ocean Crest Penthouse',
    location: 'Victoria Island, Lagos',
    price: 285000000,
    type: 'Penthouse',
    status: 'sale',
    bedrooms: 4,
    bathrooms: 3,
    size: '420 sqm',
    tag: 'Featured',
    isFeatured: true,
    description: `This exceptional penthouse sits at the crown of one of Victoria Island's most prestigious addresses. Finished to an uncompromising standard, every detail has been considered — from the Italian marble flooring to the floor-to-ceiling windows that frame breathtaking ocean views.`,
    features: ['Ocean-facing wraparound terrace','Italian marble flooring throughout','Smart home automation system','Private elevator access','Chef-grade kitchen with island','2 dedicated parking spaces','24/7 security and concierge','Rooftop swimming pool access','Backup generator','Central air conditioning'],
    images: [img.penthhouse, img.int1, img.int2],
    agent, yearBuilt: 2022, parking: 2,
  },
  {
    title: 'Skyline Residences',
    location: 'Lekki Phase 1, Lagos',
    price: 9500000,
    type: 'Apartment',
    status: 'rent',
    bedrooms: 3,
    bathrooms: 2,
    size: '210 sqm',
    isFeatured: true,
    description: `Skyline Residences offers a rare combination of modern design and practical living in the heart of Lekki Phase 1.`,
    features: ['Fitted kitchen with modern appliances','Ample natural light','Covered parking space','24-hour security','Backup power supply'],
    images: [img.skyline, img.kitchen, img.int1],
    agent, yearBuilt: 2020, parking: 1,
  },
  {
    title: 'The Garden Estate',
    location: 'Maitama, Abuja',
    price: 180000000,
    type: 'Duplex',
    status: 'sale',
    bedrooms: 5,
    bathrooms: 4,
    size: '380 sqm',
    tag: 'New',
    isFeatured: true,
    description: `Set within a beautifully landscaped estate in the diplomatic heart of Abuja.`,
    features: ['Private landscaped garden','All en-suite bedrooms','Boys quarters','Double garage','Solar power backup'],
    images: [img.duplex, img.duplex3, img.int3],
    agent, yearBuilt: 2023, parking: 2,
  },
  {
    title: 'Harbour View Suites',
    location: 'Oniru, Lagos',
    price: 75000000,
    type: 'Apartment',
    status: 'sale',
    bedrooms: 2,
    bathrooms: 2,
    size: '165 sqm',
    isFeatured: true,
    description: `Harbour View Suites is a sophisticated residential development in the rapidly growing Oniru district.`,
    features: ['Harbour views from living area','Secure underground parking','Swimming pool','Gym facility','Fibre internet ready'],
    images: [img.apart2, img.livingroom, img.int4],
    agent, yearBuilt: 2021, parking: 1,
  },
  {
    title: 'Asokoro Grand Villa',
    location: 'Asokoro, Abuja',
    price: 450000000,
    type: 'Villa',
    status: 'sale',
    bedrooms: 6,
    bathrooms: 5,
    size: '600 sqm',
    tag: 'Premium',
    isFeatured: true,
    description: `The Asokoro Grand Villa is one of Abuja's finest residential offerings.`,
    features: ['Private swimming pool','Home cinema room','Full staff quarters','Triple garage','Smart security system','Tennis court'],
    images: [img.villa, img.swim, img.int5],
    agent, yearBuilt: 2021, parking: 3,
  },
  {
    title: 'Ikoyi Luxury Flats',
    location: 'Ikoyi, Lagos',
    price: 25000,
    type: 'Apartment',
    status: 'shortlet',
    bedrooms: 2,
    bathrooms: 2,
    size: '140 sqm',
    isFeatured: true,
    description: `Experience the finest short-let accommodation in Lagos right in the heart of Ikoyi.`,
    features: ['Fully furnished to hotel standard','High-speed Wi-Fi','Smart TV with Netflix','Housekeeping included','Airport pickup available'],
    images: [img.apart3, img.int2, img.kitchen],
    agent, yearBuilt: 2019, parking: 1,
  },
  {
    title: 'Banana Island Court',
    location: 'Banana Island, Lagos',
    price: 850000000,
    type: 'Mansion',
    status: 'sale',
    bedrooms: 7,
    bathrooms: 6,
    size: '900 sqm',
    tag: 'Premium',
    isFeatured: false,
    description: `An extraordinary mansion on Nigeria's most exclusive address.`,
    features: ['Waterfront access','Indoor swimming pool','Private gym','Wine cellar','Quadruple garage','Tennis court','Helipad ready'],
    images: [img.mansion, img.swim, img.int1],
    agent, yearBuilt: 2023, parking: 4,
  },
  {
    title: 'Wuse II Business Hub',
    location: 'Wuse II, Abuja',
    price: 12000000,
    type: 'Commercial',
    status: 'rent',
    size: '320 sqm',
    isFeatured: false,
    description: `A premium commercial space in the most active business district in Abuja.`,
    features: ['Open plan floor plate','24-hour power supply','High-speed internet infrastructure','Secure car park','CCTV throughout'],
    images: [img.commercial, img.architect],
    agent, yearBuilt: 2018, parking: 10,
  },
  {
    title: 'Lekki Gardens Terrace',
    location: 'Lekki Phase 2, Lagos',
    price: 55000000,
    type: 'Terrace',
    status: 'sale',
    bedrooms: 3,
    bathrooms: 3,
    size: '200 sqm',
    tag: 'New',
    isFeatured: false,
    description: `A brand new terrace home within a well-managed gated estate in Lekki Phase 2.`,
    features: ['Private rear courtyard','All-ensuite bedrooms','Estate swimming pool','Estate security'],
    images: [img.terra, img.kitchen, img.int3],
    agent, yearBuilt: 2024, parking: 1,
  },
  {
    title: 'Gwarinpa Family Home',
    location: 'Gwarinpa, Abuja',
    price: 4800000,
    type: 'Duplex',
    status: 'rent',
    bedrooms: 4,
    bathrooms: 3,
    size: '280 sqm',
    isFeatured: false,
    description: `A spacious and well-maintained family duplex in the heart of Gwarinpa.`,
    features: ['Large compound with garden','Boys quarters','Ample parking space','Borehole water supply'],
    images: [img.im1, img.im2, img.im3],
    agent, yearBuilt: 2017, parking: 3,
  },
  {
    title: 'Eko Atlantic Apartment',
    location: 'Eko Atlantic, Lagos',
    price: 320000000,
    type: 'Apartment',
    status: 'sale',
    bedrooms: 3,
    bathrooms: 3,
    size: '250 sqm',
    tag: 'Featured',
    isFeatured: false,
    description: `Be part of Lagos's most ambitious urban development.`,
    features: ['Panoramic ocean views','Smart home system','Concierge service','Underground parking','Fibre internet'],
    images: [img.apart1, img.int4, img.int5],
    agent, yearBuilt: 2023, parking: 2,
  },
  {
    title: 'Jabi Lake View Studio',
    location: 'Jabi, Abuja',
    price: 35000,
    type: 'Studio',
    status: 'shortlet',
    bedrooms: 1,
    bathrooms: 1,
    size: '65 sqm',
    isFeatured: false,
    description: `A beautifully designed studio apartment overlooking the serene Jabi Lake.`,
    features: ['Lake-facing balcony','Fully equipped kitchenette','High-speed Wi-Fi','Work desk','24-hour power'],
    images: [img.studio, img.kitchen, img.int2],
    agent, yearBuilt: 2020, parking: 1,
  },
]

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      serverSelectionTimeoutMS: 30000,
      socketTimeoutMS: 45000,
    })
    console.log('MongoDB Connected')
    await Property.deleteMany()
    console.log('Old properties cleared')
    await Property.insertMany(properties)
    console.log('✅ 12 properties seeded with Cloudinary images!')
    process.exit()
  } catch (error) {
    console.error(error)
    process.exit(1)
  }
}

seedDB()